import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/components/header";

import { Providers as AuthProvider } from "@/components/provider/session-provider";
import { QueryProvider } from "@/components/provider/query-provider";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AIPrompt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider>
          <Header />
          <QueryProvider>{children}</QueryProvider>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
